# Matrix configuration
# If you only want an IRC ping bot, check out the `ping_responder` command.
matrix:
  homeserver: "https://matrix.org"
  user: "@???:matrix.org"
  token: <secret>
  # These rooms are used for active measurements to IRC.
  rooms:
    example: "!xxx:example.com"

# IRC configuration
# This can be left out to disable IRC functionality.
irc:
  ircnet:
    server: localhost:6667
    nick: PingBot
    user: PingBot
    ssl: false
    channels:
      - "#test"

